spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_example?serverTimezone=UTC
    username: root
    password: yuguangbao
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
server:
  port: 8082