package com.example.mysql2es.mybatis.mapper;

import com.example.mysql2es.mybatis.model.Usertest;
import com.example.mysql2es.mybatis.model.UsertestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsertestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertest
     *
     * @mbg.generated
     */
    long countByExample(UsertestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertest
     *
     * @mbg.generated
     */
    int deleteByExample(UsertestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertest
     *
     * @mbg.generated
     */
    int insert(Usertest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertest
     *
     * @mbg.generated
     */
    int insertSelective(Usertest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertest
     *
     * @mbg.generated
     */
    List<Usertest> selectByExample(UsertestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertest
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Usertest record, @Param("example") UsertestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertest
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Usertest record, @Param("example") UsertestExample example);
}